fruits=["Apples", "Apricots", "Avocados",
"Bananas", "Boysenberries", "Blueberries","Bing Cherry",
"Cherries", "Cantaloupe", "Crab apples", "Clementine", "Cucumbers",
"Damson plum", "Dinosaur Eggs", "Dates", "Dewberries", "Dragon Fruit",
"Elderberry", "Eggfruit", "Evergreen Huckleberry", "Entawak",
"Fig", "Farkleberry", "Finger Lime",
"Grapefruit", "Grapes", "Gooseberries", "Guava",
"Honeydew melon", "Hackberry", "Honeycrisp Apples",
"Indian Prune", "Indonesian Lime", "Imbe", "Indian Fig",
"Jackfruit", "Java Apple", "Jambolan",
"Kiwi", "Kaffir Lime", "Kumquat",
"Lime", "Longan", "Lychee", "Loquat",
"Mango", "Mandarin Orange", "Mulberry", "Melon",
"Nectarine", "Navel Orange", "Nashi Pear",
"Olive", "Oranges", "Ogeechee Limes", "Oval Kumquat",
"Papaya", "Persimmon", "Paw Paw", "Prickly Pear", "Peach", "Pomegranate", "Pineapple",
"Quince", "Queen Anne Cherry", "Quararibea cordata",
"Rambutan", "Raspberries", "Rose Hips",
"Star Fruit", "Strawberries", "Sugar Baby Watermelon",
"Tomato", "Tangerine", "Tamarind", "Tart Cherries",
"Ugli Fruit", "Uniq Fruit", "Ugni",
"Vanilla Bean", "Velvet Pink Banana", "Voavanga",
"Watermelon", "Wolfberry", "White Mulberry",
"Xigua", "Ximenia caffra fruit", "Xango Mangosteen",
"Yellow Passion Fruit", "Yunnan Hackberry", "Yangmei",
"Zig Zag Vine fruit", "Zinfandel Grapes", "Zucchini"]

animals=["Aardvark",
"Aardwolf",
"African Elephant",
"African Tree Pangolin",
"Alligator",
"Alpaca",
"Anteater",
"Antelope",
"Ape",
"Arabian Horse",
"Armadillo",
"Arthropod",
"Asian Elephant",
"Aye-Aye",
"Baboon",
"Badger",
"Bandicoot",
"Bangle Tiger",
"Bat",
"Bearded Dragon",
"Beaver",
"Beluga Whale",
"Bengal Tiger",
"Big-Horned Sheep",
"Billy Goat",
"Bird",
"Bison",
"Black Bear",
"Black Footed Rhino",
"Black Howler Monkey",
"Black Rhino",
"Blacktip Reef Shark",
"Blue Shark",
"Blue Whale",
"Boar",
"Bob-Cat",
"Bonobo",
"Bottlenose Dolphin",
"Bottlenose Whale",
"Brown Bear",
"Buffalo",
"Bull",
"Bull frog",
"Caiman Lizard",
"Camel",
"Capuchin Monkey",
"Capybara",
"Caribou",
"Cat",
"Cattle",
"Cheetah",
"Chimpanzee",
"Chinchilla",
"Chipmunk",
"Common Dolphin",
"Common Seal",
"Coral and Anemone",
"Cougar",
"Cow",
"Coyote",
"Crocodile",
"Crustacean",
"Dart Frog",
"Deer",
"Degus",
"Dik-Dik",
"Dingo",
"Dog",
"Dogfish Shark",
"Dolphin",
"Donkey",
"Door Mouse",
"Dormouse",
"Draft Horse",
"Duckbill Platypus",
"Dugong",
"Dusky Shark",
"Elephant",
"Elephant Seal",
"Elk",
"Ermine",
"Eurasian Lynx",
"Ferret",
"Fish",
"Florida Panther",
"Flying Fox",
"Fox",
"Fresh Water Crocodile",
"Frog",
"Fur Seal",
"Galapagos Land Iguana",
"Galapagos Shark",
"Galapagos Tortoise",
"Gazelle",
"Gecko",
"Giant Anteater",
"Giant Panda",
"Gibbon",
"Giraffe",
"Goat",
"Gopher",
"Gorilla",
"Gray Fox",
"Gray Nurse Shark",
"Gray Reef Shark",
"Gray Whale",
"Great White Shark",
"Green Poison Dart Frog",
"Green Sea Turtle",
"Grizzly Bear",
"Groundhog",
"Guinea Pig",
"Hairy-Nosed Wombat",
"Hammerhead Shark",
"Harbor Porpoise",
"Harbor Seal",
"Hare",
"Harp Seal",
"Hawaiian Monk Seal",
"Hedgehog",
"Hippopotamus",
"Horn Shark",
"Horse",
"Howler Monkey",
"Humpback Whale",
"Hyena",
"Hyrax",
"Iguana",
"Iguanodon",
"Impala",
"Insect",
"Irrawaddy Dolphin",
"Jackal",
"Jackrabbit",
"Jaguar",
"Kangaroo",
"Kermode Bear",
"Killer Whale",
"Koala",
"Komodo Dragon",
"Kookaburra",
"Lama",
"Lamb",
"Lancelet",
"Least Weasel",
"Leatherback Sea Turtle",
"Lemming",
"Lemon Shark",
"Lemur",
"Leopard",
"Leopard Gecko",
"Leopard Seal",
"Leopard Shark",
"Lion",
"Llama",
"Loggerhead Turtles",
"Lynx",
"Mako Shark",
"Manatee",
"Manta Ray",
"Mantis",
"Marbled Salamander",
"Marmot",
"Marsupial",
"Meerkat",
"Megamouth Shark",
"Melon-Headed Whale",
"Miniature Donkey",
"Mink",
"Minke Whale",
"Mole",
"Mole Salamander",
"Mollusk",
"Mongoose",
"Monitor Lizard",
"Monk Seal",
"Monkey",
"Moose",
"Mountain Lion",
"Mouse",
"Mule",
"Muskox",
"Muskrat",
"Naked Mole Rat",
"Narwhal",
"Nautilus",
"Newt",
"Northern Right Whale",
"Nurse Shark",
"Nutria",
"Nyala",
"Ocelot",
"Octopus",
"Okapi",
"Opossum",
"Orangutan",
"Orca",
"Otter",
"Ox",
"Panda",
"Panther",
"Pig",
"Pilot Whale",
"Pine Marten",
"Platypus",
"Polar Bear",
"Porcupine",
"Porpoise",
"Possum",
"Potbellied Pig",
"Potto",
"Prairie Dog",
"Proboscis Monkey",
"Puma",
"Pygmy Hippopotamus",
"Pygmy Right Whale",
"Pygmy Sperm Whale",
"Quokkas",
"Quolls",
"Rabbit",
"Raccoon",
"Rat",
"Ray",
"Red Fox",
"Red Kangaroo",
"Red Panda",
"Red-Eyed Tree Frog",
"Reef Shark",
"Reindeer",
"Rhino",
"Rhinoceros",
"Right Whale",
"Ringed Seal",
"Risso's Dolphin",
"River Dolphin",
"Salamander",
"Sandbar Shark",
"Scalloped Hammerhead Shark",
"Sea Lion",
"Sea Turtles",
"Seal",
"Sei Whale",
"Shark",
"Sheep",
"Shortfin Mako Shark",
"Siberian Tiger",
"Silky Shark",
"Skink",
"Skunk",
"Slender Loris",
"Sloth",
"Sloth Bear",
"Snake",
"Snow Fox",
"Snow Hare",
"Snow Leopard",
"Snow Monkey",
"Somali Wild Ass",
"Spectacled Bear",
"Sperm Whale",
"Spider Monkey",
"Spiny Dogfish Shark",
"Spotted Dolphin",
"Squirrel",
"Star-Nosed Mole",
"Stellar Sea Lion",
"Striped Dolphin",
"Sun Bear",
"Takin",
"Tamarin",
"Tapir",
"Tasmanian Devil",
"Tasmanian Tiger",
"Terrapin",
"Thresher Shark",
"Tiger",
"Tiger Salamander",
"Tiger Shark",
"Topi",
"Tortoise",
"Tree Frog",
"Turtle",
"Uakari",
"Vampire Bat",
"Vancouver Island Marmot",
"Vervet Monkey",
"Vicuna",
"Vole",
"Wallaby",
"Walrus",
"Warthog",
"Water Buffalo",
"Weasel",
"Whale Shark",
"Whale",
"White Rhino",
"White Tailed Deer",
"White-Beaked Dolphin",
"Whitetip Reef Shark",
"Wildcat",
"Wildebeest",
"Wobbegong Shark",
"Wolf",
"Wolverine",
"Wombat",
"Woodchuck",
"Yak",
"Yellow-Bellied Marmot",
"Zebra",
"Zebu",
"Zorilla"]

places=["Afghanistan",
"Akrotiri",
"Albania",
"Algeria",
"American Samoa",
"Andorra",
"Angola",
"Anguilla",
"Antarctica",
"Argentina",
"Armenia",
"Aruba",
"Australia",
"Austria",
"Azerbaijan",
"Bangladesh",
"Barbados",
"Bassas da India",
"Belarus",
"Belgium",
"Belize",
"Benin",
"Bermuda",
"Bhutan",
"Bolivia",
"Botswana",
"Bouvet Island",
"Brazil",
"British Indian Ocean Territory",
"British Virgin Islands",
"Brunei",
"Bulgaria",
"Burkina Faso",
"Burma",
"Burundi",
"Cambodia",
"Cameroon",
"Canada",
"Cape Verde",
"Cayman Islands",
"Central African Republic",
"Chad",
"Chile",
"China",
"Christmas Island",
"Clipperton Island",
"Cocos Islands",
"Colombia",
"Comoros",
"Cook Islands",
"Coral Sea Islands",
"Costa Rica",
"Croatia",
"Cuba",
"Cyprus",
"Czech Republic",
"Denmark",
"Dhekelia",
"Djibouti",
"Dominica",
"Dominican Republic",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Ethiopia",
"Europa Island",
"Faroe Islands",
"Finland",
"France",
"French Guiana",
"French Polynesia",
"Gabon",
"Gambia, The",
"Gaza Strip",
"Georgia",
"Germany",
"Ghana",
"Gibraltar",
"Glorioso Islands",
"Greece",
"Greenland",
"Grenada",
"Guadeloupe",
"Guam",
"Guatemala",
"Guernsey",
"Guinea",
"Guinea-Bissau",
"Guyana",
"Haiti",
"Honduras",
"Hong Kong",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran",
"Iraq",
"Ireland",
"Isle of Man",
"Israel",
"Italy",
"Jamaica",
"Jan Mayen",
"Japan",
"Jersey",
"Jordan",
"Juan de Nova Island",
"Kazakhstan",
"Kenya",
"Kiribati",
"Korea, North",
"Korea, South",
"Kuwait",
"Kyrgyzstan",
"Laos",
"Latvia",
"Lebanon",
"Lesotho",
"Liberia",
"Libya",
"Liechtenstein",
"Lithuania",
"Luxembourg",
"Macau",
"Macedonia",
"Madagascar",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall Islands",
"Martinique",
"Mauritania",
"Mauritius",
"Mayotte",
"Mexico",
"Monaco",
"Mongolia",
"Montserrat",
"Morocco",
"Mozambique",
"Namibia",
"Nauru",
"Navassa Island",
"Nepal",
"Netherlands",
"Netherlands Antilles",
"New Caledonia",
"New Zealand",
"Nicaragua",
"Niger",
"Nigeri",
"Niue",
"Norfolk Island",
"Northern Mariana Islands",
"Norway",
"Oman",
"Pakistan",
"Palau",
"Panama",
"Papua New Guinea",
"Paracel Islands",
"Paraguay",
"Peru",
"Philippines",
"Pitcairn Islands",
"Poland",
"Portugal",
"Puerto Rico",
"Qatar",
"Reunion",
"Romania",
"Russia",
"Rwanda",
"Saint Helena",
"Saint Lucia",
"Samoa",
"San Marino",
"Saudi Arabia",
"Senegal",
"Seychelles",
"Sierra Leone",
"Singapore",
"Slovakia",
"Slovenia",
"Solomon Islands",
"Somalia",
"South Africa",
"Spain",
"Spratly Islands",
"Sri Lanka",
"Sudan",
"Suriname",
"Svalbard",
"Swaziland",
"Sweden",
"Switzerland",
"Syria",
"Taiwan",
"Tajikistan",
"Tanzania",
"Thailand",
"Timor-Leste",
"Togo",
"Tokelau",
"Tonga",
"Tromelin Island",
"Tunisia",
"Turkey",
"Turkmenistan",
"Tuvalu",
"Uganda",
"Ukraine",
"United Arab Emirates",
"United Kingdom",
"United States",
"Uruguay",
"Uzbekistan",
"Vanuatu",
"Venezuela",
"Vietnam",
"Virgin Islands",
"Wake Island",
"West Bank",
"Western Sahara",
"Yemen",
"Zambia",
"Zimbabwe"]

randoms=["Apples", "Apricots", "Avocados",
"Bananas", "Boysenberries", "Blueberries","Bing Cherry",
"Cherries", "Cantaloupe", "Crab apples", "Clementine", "Cucumbers",
"Damson plum", "Dinosaur Eggs", "Dates", "Dewberries", "Dragon Fruit",
"Elderberry", "Eggfruit", "Evergreen Huckleberry", "Entawak",
"Fig", "Farkleberry", "Finger Lime",
"Grapefruit", "Grapes", "Gooseberries", "Guava",
"Honeydew melon", "Hackberry", "Honeycrisp Apples",
"Indian Prune", "Indonesian Lime", "Imbe", "Indian Fig",
"Jackfruit", "Java Apple", "Jambolan",
"Kiwi", "Kaffir Lime", "Kumquat",
"Lime", "Longan", "Lychee", "Loquat",
"Mango", "Mandarin Orange", "Mulberry", "Melon",
"Nectarine", "Navel Orange", "Nashi Pear",
"Olive", "Oranges", "Ogeechee Limes", "Oval Kumquat",
"Papaya", "Persimmon", "Paw Paw", "Prickly Pear", "Peach", "Pomegranate", "Pineapple",
"Quince", "Queen Anne Cherry", "Quararibea cordata",
"Rambutan", "Raspberries", "Rose Hips",
"Star Fruit", "Strawberries", "Sugar Baby Watermelon",
"Tomato", "Tangerine", "Tamarind", "Tart Cherries",
"Ugli Fruit", "Uniq Fruit", "Ugni",
"Vanilla Bean", "Velvet Pink Banana", "Voavanga",
"Watermelon", "Wolfberry", "White Mulberry",
"Xigua", "Ximenia caffra fruit", "Xango Mangosteen",
"Yellow Passion Fruit", "Yunnan Hackberry", "Yangmei",
"Zig Zag Vine fruit", "Zinfandel Grapes", "Zucchini",
"Aardvark",
"Aardwolf",
"African Elephant",
"African Tree Pangolin",
"Alligator",
"Alpaca",
"Anteater",
"Antelope",
"Ape",
"Arabian Horse",
"Armadillo",
"Arthropod",
"Asian Elephant",
"Aye-Aye",
"Baboon",
"Badger",
"Bandicoot",
"Bangle Tiger",
"Bat",
"Bearded Dragon",
"Beaver",
"Beluga Whale",
"Bengal Tiger",
"Big-Horned Sheep",
"Billy Goat",
"Bird",
"Bison",
"Black Bear",
"Black Footed Rhino",
"Black Howler Monkey",
"Black Rhino",
"Blacktip Reef Shark",
"Blue Shark",
"Blue Whale",
"Boar",
"Bob-Cat",
"Bonobo",
"Bottlenose Dolphin",
"Bottlenose Whale",
"Brown Bear",
"Buffalo",
"Bull",
"Bull frog",
"Caiman Lizard",
"Camel",
"Capuchin Monkey",
"Capybara",
"Caribou",
"Cat",
"Cattle",
"Cheetah",
"Chimpanzee",
"Chinchilla",
"Chipmunk",
"Common Dolphin",
"Common Seal",
"Coral and Anemone",
"Cougar",
"Cow",
"Coyote",
"Crocodile",
"Crustacean",
"Dart Frog",
"Deer",
"Degus",
"Dik-Dik",
"Dingo",
"Dog",
"Dogfish Shark",
"Dolphin",
"Donkey",
"Door Mouse",
"Dormouse",
"Draft Horse",
"Duckbill Platypus",
"Dugong",
"Dusky Shark",
"Elephant",
"Elephant Seal",
"Elk",
"Ermine",
"Eurasian Lynx",
"Ferret",
"Fish",
"Florida Panther",
"Flying Fox",
"Fox",
"Fresh Water Crocodile",
"Frog",
"Fur Seal",
"Galapagos Land Iguana",
"Galapagos Shark",
"Galapagos Tortoise",
"Gazelle",
"Gecko",
"Giant Anteater",
"Giant Panda",
"Gibbon",
"Giraffe",
"Goat",
"Gopher",
"Gorilla",
"Gray Fox",
"Gray Nurse Shark",
"Gray Reef Shark",
"Gray Whale",
"Great White Shark",
"Green Poison Dart Frog",
"Green Sea Turtle",
"Grizzly Bear",
"Groundhog",
"Guinea Pig",
"Hairy-Nosed Wombat",
"Hammerhead Shark",
"Harbor Porpoise",
"Harbor Seal",
"Hare",
"Harp Seal",
"Hawaiian Monk Seal",
"Hedgehog",
"Hippopotamus",
"Horn Shark",
"Horse",
"Howler Monkey",
"Humpback Whale",
"Hyena",
"Hyrax",
"Iguana",
"Iguanodon",
"Impala",
"Insect",
"Irrawaddy Dolphin",
"Jackal",
"Jackrabbit",
"Jaguar",
"Kangaroo",
"Kermode Bear",
"Killer Whale",
"Koala",
"Komodo Dragon",
"Kookaburra",
"Lama",
"Lamb",
"Lancelet",
"Least Weasel",
"Leatherback Sea Turtle",
"Lemming",
"Lemon Shark",
"Lemur",
"Leopard",
"Leopard Gecko",
"Leopard Seal",
"Leopard Shark",
"Lion",
"Llama",
"Loggerhead Turtles",
"Lynx",
"Mako Shark",
"Manatee",
"Manta Ray",
"Mantis",
"Marbled Salamander",
"Marmot",
"Marsupial",
"Meerkat",
"Megamouth Shark",
"Melon-Headed Whale",
"Miniature Donkey",
"Mink",
"Minke Whale",
"Mole",
"Mole Salamander",
"Mollusk",
"Mongoose",
"Monitor Lizard",
"Monk Seal",
"Monkey",
"Moose",
"Mountain Lion",
"Mouse",
"Mule",
"Muskox",
"Muskrat",
"Naked Mole Rat",
"Narwhal",
"Nautilus",
"Newt",
"Northern Right Whale",
"Nurse Shark",
"Nutria",
"Nyala",
"Ocelot",
"Octopus",
"Okapi",
"Opossum",
"Orangutan",
"Orca",
"Otter",
"Ox",
"Panda",
"Panther",
"Pig",
"Pilot Whale",
"Pine Marten",
"Platypus",
"Polar Bear",
"Porcupine",
"Porpoise",
"Possum",
"Potbellied Pig",
"Potto",
"Prairie Dog",
"Proboscis Monkey",
"Puma",
"Pygmy Hippopotamus",
"Pygmy Right Whale",
"Pygmy Sperm Whale",
"Quokkas",
"Quolls",
"Rabbit",
"Raccoon",
"Rat",
"Ray",
"Red Fox",
"Red Kangaroo",
"Red Panda",
"Red-Eyed Tree Frog",
"Reef Shark",
"Reindeer",
"Rhino",
"Rhinoceros",
"Right Whale",
"Ringed Seal",
"Risso's Dolphin",
"River Dolphin",
"Salamander",
"Sandbar Shark",
"Scalloped Hammerhead Shark",
"Sea Lion",
"Sea Turtles",
"Seal",
"Sei Whale",
"Shark",
"Sheep",
"Shortfin Mako Shark",
"Siberian Tiger",
"Silky Shark",
"Skink",
"Skunk",
"Slender Loris",
"Sloth",
"Sloth Bear",
"Snake",
"Snow Fox",
"Snow Hare",
"Snow Leopard",
"Snow Monkey",
"Somali Wild Ass",
"Spectacled Bear",
"Sperm Whale",
"Spider Monkey",
"Spiny Dogfish Shark",
"Spotted Dolphin",
"Squirrel",
"Star-Nosed Mole",
"Stellar Sea Lion",
"Striped Dolphin",
"Sun Bear",
"Takin",
"Tamarin",
"Tapir",
"Tasmanian Devil",
"Tasmanian Tiger",
"Terrapin",
"Thresher Shark",
"Tiger",
"Tiger Salamander",
"Tiger Shark",
"Topi",
"Tortoise",
"Tree Frog",
"Turtle",
"Uakari",
"Vampire Bat",
"Vancouver Island Marmot",
"Vervet Monkey",
"Vicuna",
"Vole",
"Wallaby",
"Walrus",
"Warthog",
"Water Buffalo",
"Weasel",
"Whale Shark",
"Whale",
"White Rhino",
"White Tailed Deer",
"White-Beaked Dolphin",
"Whitetip Reef Shark",
"Wildcat",
"Wildebeest",
"Wobbegong Shark",
"Wolf",
"Wolverine",
"Wombat",
"Woodchuck",
"Yak",
"Yellow-Bellied Marmot",
"Zebra",
"Zebu",
"Zorilla",
"Afghanistan",
"Akrotiri",
"Albania",
"Algeria",
"American Samoa",
"Andorra",
"Angola",
"Anguilla",
"Antarctica",
"Argentina",
"Armenia",
"Aruba",
"Australia",
"Austria",
"Azerbaijan",
"Bangladesh",
"Barbados",
"Bassas da India",
"Belarus",
"Belgium",
"Belize",
"Benin",
"Bermuda",
"Bhutan",
"Bolivia",
"Botswana",
"Bouvet Island",
"Brazil",
"British Indian Ocean Territory",
"British Virgin Islands",
"Brunei",
"Bulgaria",
"Burkina Faso",
"Burma",
"Burundi",
"Cambodia",
"Cameroon",
"Canada",
"Cape Verde",
"Cayman Islands",
"Central African Republic",
"Chad",
"Chile",
"China",
"Christmas Island",
"Clipperton Island",
"Cocos Islands",
"Colombia",
"Comoros",
"Cook Islands",
"Coral Sea Islands",
"Costa Rica",
"Croatia",
"Cuba",
"Cyprus",
"Czech Republic",
"Denmark",
"Dhekelia",
"Djibouti",
"Dominica",
"Dominican Republic",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Ethiopia",
"Europa Island",
"Faroe Islands",
"Finland",
"France",
"French Guiana",
"French Polynesia",
"Gabon",
"Gambia, The",
"Gaza Strip",
"Georgia",
"Germany",
"Ghana",
"Gibraltar",
"Glorioso Islands",
"Greece",
"Greenland",
"Grenada",
"Guadeloupe",
"Guam",
"Guatemala",
"Guernsey",
"Guinea",
"Guinea-Bissau",
"Guyana",
"Haiti",
"Honduras",
"Hong Kong",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran",
"Iraq",
"Ireland",
"Isle of Man",
"Israel",
"Italy",
"Jamaica",
"Jan Mayen",
"Japan",
"Jersey",
"Jordan",
"Juan de Nova Island",
"Kazakhstan",
"Kenya",
"Kiribati",
"Korea, North",
"Korea, South",
"Kuwait",
"Kyrgyzstan",
"Laos",
"Latvia",
"Lebanon",
"Lesotho",
"Liberia",
"Libya",
"Liechtenstein",
"Lithuania",
"Luxembourg",
"Macau",
"Macedonia",
"Madagascar",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall Islands",
"Martinique",
"Mauritania",
"Mauritius",
"Mayotte",
"Mexico",
"Monaco",
"Mongolia",
"Montserrat",
"Morocco",
"Mozambique",
"Namibia",
"Nauru",
"Navassa Island",
"Nepal",
"Netherlands",
"Netherlands Antilles",
"New Caledonia",
"New Zealand",
"Nicaragua",
"Niger",
"Nigeri",
"Niue",
"Norfolk Island",
"Northern Mariana Islands",
"Norway",
"Oman",
"Pakistan",
"Palau",
"Panama",
"Papua New Guinea",
"Paracel Islands",
"Paraguay",
"Peru",
"Philippines",
"Pitcairn Islands",
"Poland",
"Portugal",
"Puerto Rico",
"Qatar",
"Reunion",
"Romania",
"Russia",
"Rwanda",
"Saint Helena",
"Saint Lucia",
"Samoa",
"San Marino",
"Saudi Arabia",
"Senegal",
"Seychelles",
"Sierra Leone",
"Singapore",
"Slovakia",
"Slovenia",
"Solomon Islands",
"Somalia",
"South Africa",
"Spain",
"Spratly Islands",
"Sri Lanka",
"Sudan",
"Suriname",
"Svalbard",
"Swaziland",
"Sweden",
"Switzerland",
"Syria",
"Taiwan",
"Tajikistan",
"Tanzania",
"Thailand",
"Timor-Leste",
"Togo",
"Tokelau",
"Tonga",
"Tromelin Island",
"Tunisia",
"Turkey",
"Turkmenistan",
"Tuvalu",
"Uganda",
"Ukraine",
"United Arab Emirates",
"United Kingdom",
"United States",
"Uruguay",
"Uzbekistan",
"Vanuatu",
"Venezuela",
"Vietnam",
"Virgin Islands",
"Wake Island",
"West Bank",
"Western Sahara",
"Yemen",
"Zambia",
"Zimbabwe"]
